[prerender]
enabled = false

[[headers]]
for = "/robots.txt"
[headers.values]
  Cache-Control = "no-store"
  Content-Type = "text/plain"

[[headers]]
for = "/sitemap*.xml"
[headers.values]
  Cache-Control = "no-store"
  Content-Type = "application/xml"
